import React,{useEffect,useState} from "react";
import {Routes,Route,Link,useNavigate} from "react-router-dom";
import {api} from "./api";
import {BarChart,Bar,XAxis,YAxis,Tooltip,ResponsiveContainer} from "recharts";

function Layout({children}){const nav=useNavigate();const user=JSON.parse(localStorage.getItem("user")||"null");return <><header><Link to="/"><b>LSM</b> Local Service Marketplace</Link><nav>{user?<><Link to="/dashboard">Dashboard</Link><button onClick={()=>{localStorage.clear();nav("/login")}}>Logout</button></>:<><Link to="/login">Login</Link><Link to="/register">Register</Link></>}</nav></header><main>{children}</main></>}
function Home(){const [services,setServices]=useState([]);const [q,setQ]=useState("");useEffect(()=>{api("/services").then(setServices)},[]);const search=()=>api("/services?q="+encodeURIComponent(q)).then(setServices);return <section><div className="hero"><h1>Find trusted local services</h1><p>Book verified professionals for plumbing, electrical, cleaning and more.</p><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search service"/><button onClick={search}>Search</button></div><h2>Available Services</h2><div className="grid">{services.map(s=><div className="card" key={s._id}><h3>{s.name}</h3><p>{s.category}</p><p>{s.description}</p><b>₹{s.basePrice}</b><p>Provider: {s.provider?.name} · Trust {s.provider?.trustScore}</p><Link className="btn" to="/book">Book Service</Link></div>)}</div></section>}
function Auth({register=false}){const nav=useNavigate();const [form,setForm]=useState({name:"",email:"",password:"",role:"customer"});const submit=async e=>{e.preventDefault();try{const d=await api(register?"/auth/register":"/auth/login",{method:"POST",body:JSON.stringify(form)});localStorage.setItem("token",d.token);localStorage.setItem("user",JSON.stringify(d.user));nav("/dashboard")}catch(e){alert(e.message)}};return <div className="form"><h2>{register?"Create Account":"Login"}</h2>{register&&<input placeholder="Name" onChange={e=>setForm({...form,name:e.target.value})}/>}<input placeholder="Email" type="email" onChange={e=>setForm({...form,email:e.target.value})}/><input placeholder="Password" type="password" onChange={e=>setForm({...form,password:e.target.value})}/>{register&&<select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option value="customer">Customer</option><option value="provider">Service Provider</option></select>}<button onClick={submit}>{register?"Register":"Login"}</button></div>}
function Book(){const nav=useNavigate();const [services,setServices]=useState([]);const [f,setF]=useState({serviceId:"",bookingType:"normal",scheduledAt:"",address:"",notes:""});useEffect(()=>api("/services").then(setServices),[]);const submit=async e=>{e.preventDefault();try{await api("/bookings",{method:"POST",body:JSON.stringify(f)});alert("Booking created");nav("/dashboard")}catch(e){alert(e.message)}};return <div className="form"><h2>Book a Service</h2><select onChange={e=>setF({...f,serviceId:e.target.value})}><option value="">Select service</option>{services.map(s=><option value={s._id} key={s._id}>{s.name} - ₹{s.basePrice}</option>)}</select><select onChange={e=>setF({...f,bookingType:e.target.value})}><option value="normal">Normal Booking</option><option value="emergency">Emergency Booking</option></select><input type="datetime-local" onChange={e=>setF({...f,scheduledAt:e.target.value})}/><input placeholder="Service address" onChange={e=>setF({...f,address:e.target.value})}/><textarea placeholder="Notes / requirements" onChange={e=>setF({...f,notes:e.target.value})}/><button onClick={submit}>Confirm Booking</button></div>}
function Dashboard(){const user=JSON.parse(localStorage.getItem("user")||"null");return user?.role==="admin"?<Admin/>:<UserDashboard/>}
function UserDashboard(){const user=JSON.parse(localStorage.getItem("user")||"null");const [items,setItems]=useState([]);useEffect(()=>api("/bookings/mine").then(setItems),[]);const status=async(id,s)=>{await api("/bookings/"+id+"/status",{method:"PATCH",body:JSON.stringify({status:s})});setItems(await api("/bookings/mine"))};const pay=async id=>{await api("/bookings/"+id+"/payment",{method:"PATCH",body:"{}"});setItems(await api("/bookings/mine"))};return <section><h2>{user?.role==="provider"?"Provider":"Customer"} Dashboard</h2><div className="grid">{items.map(b=><div className="card" key={b._id}><h3>{b.service?.name}</h3><p>Customer: {b.customer?.name}</p><p>Provider: {b.provider?.name}</p><p>Status: <b>{b.status}</b> · Payment: {b.paymentStatus}</p><p>Type: {b.bookingType} · Amount ₹{b.amount}</p>{user?.role==="provider"&&b.status==="pending"&&<><button onClick={()=>status(b._id,"accepted")}>Accept</button><button onClick={()=>status(b._id,"rejected")}>Reject</button></>}{user?.role==="provider"&&b.status==="accepted"&&<button onClick={()=>status(b._id,"in-progress")}>Start Job</button>}{user?.role==="provider"&&b.status==="in-progress"&&<button onClick={()=>status(b._id,"completed")}>Mark Completed</button>}{user?.role==="customer"&&b.paymentStatus==="pending"&&<button onClick={()=>pay(b._id)}>Pay Now</button>}<a className="btn" href={`http://localhost:5000/api/invoices/${b._id}/pdf`} target="_blank">Invoice</a>{b.qrData&&<details><summary>QR Completion Code</summary><img src={b.qrData} width="180"/></details>}</div>)}</div></section>}
function Admin(){const [d,setD]=useState(null);useEffect(()=>api("/admin/dashboard").then(setD),[]);if(!d)return <p>Loading analytics...</p>;return <section><h2>Admin Analytics Dashboard</h2><div className="stats"><div>Users <b>{d.users}</b></div><div>Providers <b>{d.providers}</b></div><div>Services <b>{d.services}</b></div><div>Bookings <b>{d.bookings}</b></div><div>Revenue <b>₹{d.revenue}</b></div></div><div className="chart"><ResponsiveContainer width="100%" height={300}><BarChart data={d.status.map(x=>({name:x._id,count:x.count}))}><XAxis dataKey="name"/><YAxis/><Tooltip/><Bar dataKey="count"/></BarChart></ResponsiveContainer></div></section>}
export default function App(){return <Layout><Routes><Route path="/" element={<Home/>}/><Route path="/login" element={<Auth/>}/><Route path="/register" element={<Auth register/>}/><Route path="/book" element={<Book/>}/><Route path="/dashboard" element={<Dashboard/>}/></Routes></Layout>}